# Regenerates Properties/Localisation.Designer.cs from Properties/Localisation.resx.
# Visual Studio does this automatically when the .resx is saved; run this script after editing the .resx
# if you only build with the dotnet CLI.
param(
    [string]$ResxPath = (Join-Path $PSScriptRoot 'YTWin-RichPresence/Properties/Localisation.resx'),
    [string]$OutPath = (Join-Path $PSScriptRoot 'YTWin-RichPresence/Properties/Localisation.Designer.cs')
)

$xml = [xml]::new()
$xml.Load((Resolve-Path $ResxPath).Path)
$entries = @($xml.root.data | Where-Object { -not $_.GetAttribute('type') -and -not $_.GetAttribute('mimetype') } | Sort-Object -Property name)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.Append(@'
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTWin_RichPresence.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YTWin_RichPresence.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
'@)

foreach ($entry in $entries) {
    $name = $entry.name
    $value = [string]$entry.value
    $summary = ($value -replace '\s+', ' ').Trim()
    if ($summary.Length -gt 80) {
        $summary = $summary.Substring(0, 80) + ' [rest of string was truncated]";.'
    }
    $summary = $summary.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
    [void]$sb.Append(@"
        
        /// <summary>
        ///   Looks up a localized string similar to $summary.
        /// </summary>
        public static string $name {
            get {
                return ResourceManager.GetString("$name", resourceCulture);
            }
        }
"@)
}

[void]$sb.Append(@'

    }
}

'@)

$content = $sb.ToString().Replace("`r`n", "`n").Replace("`n", "`r`n")
[System.IO.File]::WriteAllText((Join-Path (Split-Path (Resolve-Path $ResxPath).Path) (Split-Path $OutPath -Leaf)), $content, [System.Text.UTF8Encoding]::new($true))
Write-Host "Generated $OutPath with $($entries.Count) strings"
