//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTWin_RichPresence.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YTWin_RichPresence.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Listen on YouTube Music.
        /// </summary>
        public static string DiscordButton_ListenOnYouTubeMusic {
            get {
                return ResourceManager.GetString("DiscordButton_ListenOnYouTubeMusic", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to View channel.
        /// </summary>
        public static string DiscordButton_ViewArtist {
            get {
                return ResourceManager.GetString("DiscordButton_ViewArtist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Watch on YouTube.
        /// </summary>
        public static string DiscordButton_WatchOnYouTube {
            get {
                return ResourceManager.GetString("DiscordButton_WatchOnYouTube", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to A new update for YTWin-RP is available. Would you like to view the releases?.
        /// </summary>
        public static string Message_AppUpdate {
            get {
                return ResourceManager.GetString("Message_AppUpdate", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to New update available.
        /// </summary>
        public static string Message_AppUpdate_Title {
            get {
                return ResourceManager.GetString("Message_AppUpdate_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to All saved lyrics have been deleted..
        /// </summary>
        public static string Message_ClearedLyricCache {
            get {
                return ResourceManager.GetString("Message_ClearedLyricCache", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Deleted.
        /// </summary>
        public static string Message_ClearedLyricCache_Title {
            get {
                return ResourceManager.GetString("Message_ClearedLyricCache_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all saved lyrics?.
        /// </summary>
        public static string Message_ClearLyricCache {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete lyrics:.
        /// </summary>
        public static string Message_ClearLyricCache_Fail {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache_Fail", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to No saved lyrics found..
        /// </summary>
        public static string Message_ClearLyricCache_FailNotFound {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache_FailNotFound", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cached Lyrics.
        /// </summary>
        public static string Message_ClearLyricCache_Title {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to This build has no built-in Discord application. Enter an Application ID in the s [rest of string was truncated]";..
        /// </summary>
        public static string Message_DiscordClientIdMissing {
            get {
                return ResourceManager.GetString("Message_DiscordClientIdMissing", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Discord Application ID required.
        /// </summary>
        public static string Message_DiscordClientIdMissing_Title {
            get {
                return ResourceManager.GetString("Message_DiscordClientIdMissing_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Message_Information {
            get {
                return ResourceManager.GetString("Message_Information", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to The Last.FM credentials could not be authenticated. Please make sure you have en [rest of string was truncated]";..
        /// </summary>
        public static string Message_LastFM_Authentication_Fail {
            get {
                return ResourceManager.GetString("Message_LastFM_Authentication_Fail", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to The Last.FM credentials were successfully authenticated..
        /// </summary>
        public static string Message_LastFM_Authentication_Success {
            get {
                return ResourceManager.GetString("Message_LastFM_Authentication_Success", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Last.FM Authentication.
        /// </summary>
        public static string Message_LastFM_Authentication_Title {
            get {
                return ResourceManager.GetString("Message_LastFM_Authentication_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to The ListenBrainz credentials could not be authenticated. Please make sure you ha [rest of string was truncated]";..
        /// </summary>
        public static string Message_ListenBrainz_Authentication_Fail {
            get {
                return ResourceManager.GetString("Message_ListenBrainz_Authentication_Fail", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to The ListenBrainz credentials were successfully authenticated..
        /// </summary>
        public static string Message_ListenBrainz_Authentication_Success {
            get {
                return ResourceManager.GetString("Message_ListenBrainz_Authentication_Success", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ListenBrainz Authentication.
        /// </summary>
        public static string Message_ListenBrainz_Authentication_Title {
            get {
                return ResourceManager.GetString("Message_ListenBrainz_Authentication_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Message_No {
            get {
                return ResourceManager.GetString("Message_No", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Restart now to apply the language change?.
        /// </summary>
        public static string Message_RestartRequired_Content {
            get {
                return ResourceManager.GetString("Message_RestartRequired_Content", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string Message_RestartRequired_Title {
            get {
                return ResourceManager.GetString("Message_RestartRequired_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Message_Yes {
            get {
                return ResourceManager.GetString("Message_Yes", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Presence_Paused {
            get {
                return ResourceManager.GetString("Presence_Paused", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        public static string Presence_YouTube {
            get {
                return ResourceManager.GetString("Presence_YouTube", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Music.
        /// </summary>
        public static string Presence_YouTubeMusic {
            get {
                return ResourceManager.GetString("Presence_YouTubeMusic", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to YTWin-RP reads what your browser reports to the Windows media controls, confirms [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Detection_Description {
            get {
                return ResourceManager.GetString("Settings_Detection_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Detect music using YouTube Music.
        /// </summary>
        public static string Settings_Detection_DetectMusic {
            get {
                return ResourceManager.GetString("Settings_Detection_DetectMusic", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Videos that YouTube Music lists as songs or music videos are shown as "Listening [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Detection_DetectMusic_Description {
            get {
                return ResourceManager.GetString("Settings_Detection_DetectMusic_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to The optional extension sends the exact video ID and playback position of YouTube [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Detection_Extension_Description {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show extension folder.
        /// </summary>
        public static string Settings_Detection_Extension_OpenFolder {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_OpenFolder", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Settings_Detection_Extension_Port {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_Port", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Browser extension (optional).
        /// </summary>
        public static string Settings_Detection_Extension_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Last report from the extension: {0} seconds ago.
        /// </summary>
        public static string Settings_Detection_Extension_Status_LastReport {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_Status_LastReport", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Listening on 127.0.0.1:{0}.
        /// </summary>
        public static string Settings_Detection_Extension_Status_Listening {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_Status_Listening", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to No reports from the extension yet.
        /// </summary>
        public static string Settings_Detection_Extension_Status_NoReport {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_Status_NoReport", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Not listening.
        /// </summary>
        public static string Settings_Detection_Extension_Status_NotListening {
            get {
                return ResourceManager.GetString("Settings_Detection_Extension_Status_NotListening", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Only track YouTube while its tab is in the foreground.
        /// </summary>
        public static string Settings_Detection_RequireWindow {
            get {
                return ResourceManager.GetString("Settings_Detection_RequireWindow", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Prevents other web players in the same browser (e.g. Spotify Web) from being mis [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Detection_RequireWindow_Description {
            get {
                return ResourceManager.GetString("Settings_Detection_RequireWindow_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to YouTube detection.
        /// </summary>
        public static string Settings_Detection_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Detection_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Detection.
        /// </summary>
        public static string Settings_Detection_SectionTitleShort {
            get {
                return ResourceManager.GetString("Settings_Detection_SectionTitleShort", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show Rich Presence for music.
        /// </summary>
        public static string Settings_Detection_ShowMusic {
            get {
                return ResourceManager.GetString("Settings_Detection_ShowMusic", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show Rich Presence for videos.
        /// </summary>
        public static string Settings_Detection_ShowVideos {
            get {
                return ResourceManager.GetString("Settings_Detection_ShowVideos", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Settings_Detection_Status_Music {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_Music", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is playing on YouTube..
        /// </summary>
        public static string Settings_Detection_Status_Nothing {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_Nothing", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to via browser extension.
        /// </summary>
        public static string Settings_Detection_Status_SourceExtension {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_SourceExtension", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to via Windows media controls.
        /// </summary>
        public static string Settings_Detection_Status_SourceMediaSession {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_SourceMediaSession", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Currently detected.
        /// </summary>
        public static string Settings_Detection_Status_Title {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to not yet confirmed as YouTube.
        /// </summary>
        public static string Settings_Detection_Status_Unconfirmed {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_Unconfirmed", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Identifying….
        /// </summary>
        public static string Settings_Detection_Status_Unknown {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_Unknown", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Settings_Detection_Status_Video {
            get {
                return ResourceManager.GetString("Settings_Detection_Status_Video", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Send Rich Presence to.
        /// </summary>
        public static string Settings_Discord_ClientChoice {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientChoice", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Automatic (any running client).
        /// </summary>
        public static string Settings_Discord_ClientChoice_Auto {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientChoice_Auto", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Discord Canary.
        /// </summary>
        public static string Settings_Discord_ClientChoice_Canary {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientChoice_Canary", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Choose which Discord app receives Rich Presence when you have more than one runn [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Discord_ClientChoice_Description {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientChoice_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Discord PTB.
        /// </summary>
        public static string Settings_Discord_ClientChoice_PTB {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientChoice_PTB", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Discord (Stable).
        /// </summary>
        public static string Settings_Discord_ClientChoice_Stable {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientChoice_Stable", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        public static string Settings_Discord_ClientID {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientID", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to This build has no built-in Discord application. Create an application named "You [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Discord_ClientID_Description {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientID_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to An Application ID is a number with 17 to 20 digits..
        /// </summary>
        public static string Settings_Discord_ClientID_Invalid {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientID_Invalid", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Discord application.
        /// </summary>
        public static string Settings_Discord_ClientID_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientID_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Application ID used for music (optional).
        /// </summary>
        public static string Settings_Discord_ClientIDMusic {
            get {
                return ResourceManager.GetString("Settings_Discord_ClientIDMusic", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Enable Discord Rich Presence.
        /// </summary>
        public static string Settings_Discord_EnableRP {
            get {
                return ResourceManager.GetString("Settings_Discord_EnableRP", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Clear lyrics cache.
        /// </summary>
        public static string Settings_Discord_Lyrics_ClearCache {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_ClearCache", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show song lyrics in Rich Presence (music only).
        /// </summary>
        public static string Settings_Discord_Lyrics_EnableLyrics {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_EnableLyrics", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show lyrics cache.
        /// </summary>
        public static string Settings_Discord_Lyrics_OpenCache {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_OpenCache", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Synced Lyrics.
        /// </summary>
        public static string Settings_Discord_Lyrics_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Keep lyrics during instrumental breaks.
        /// </summary>
        public static string Settings_Discord_Lyrics_ShowDuringBreak {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_ShowDuringBreak", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to During breaks in the music, keep showing the last played lyrics..
        /// </summary>
        public static string Settings_Discord_Lyrics_ShowDuringBreak_Description {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_ShowDuringBreak_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Open Discord Developer Portal.
        /// </summary>
        public static string Settings_Discord_OpenDeveloperPortal {
            get {
                return ResourceManager.GetString("Settings_Discord_OpenDeveloperPortal", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Discord Rich Presence.
        /// </summary>
        public static string Settings_Discord_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Discord_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Discord RP.
        /// </summary>
        public static string Settings_Discord_SectionTitleShort {
            get {
                return ResourceManager.GetString("Settings_Discord_SectionTitleShort", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show thumbnail / album art.
        /// </summary>
        public static string Settings_Discord_ShowAlbumArt {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowAlbumArt", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show album or channel name when hovering the image.
        /// </summary>
        public static string Settings_Discord_ShowAlbumTitle {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowAlbumTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show YouTube icon.
        /// </summary>
        public static string Settings_Discord_ShowServiceIcon {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowServiceIcon", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Shows the YouTube or YouTube Music icon next to the thumbnail in the Rich Presen [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Discord_ShowServiceIcon_Description {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowServiceIcon_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show when playback is paused.
        /// </summary>
        public static string Settings_Discord_ShowWhenPaused {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowWhenPaused", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Show Discord status as.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay_AppName {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay_AppName", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Channel / artist name.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay_Artist {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay_Artist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Video / song title.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay_SongName {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay_SongName", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_General_Language {
            get {
                return ResourceManager.GetString("Settings_General_Language", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Restart the app after changing the language to fully apply it..
        /// </summary>
        public static string Settings_General_Language_Description {
            get {
                return ResourceManager.GetString("Settings_General_Language_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to English (English).
        /// </summary>
        public static string Settings_General_Language_English {
            get {
                return ResourceManager.GetString("Settings_General_Language_English", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to German (Deutsch).
        /// </summary>
        public static string Settings_General_Language_German {
            get {
                return ResourceManager.GetString("Settings_General_Language_German", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (日本語).
        /// </summary>
        public static string Settings_General_Language_Japanese {
            get {
                return ResourceManager.GetString("Settings_General_Language_Japanese", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Korean (한국어).
        /// </summary>
        public static string Settings_General_Language_Korean {
            get {
                return ResourceManager.GetString("Settings_General_Language_Korean", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Spanish - Latin America (Español de Latinoamérica).
        /// </summary>
        public static string Settings_General_Language_Latam {
            get {
                return ResourceManager.GetString("Settings_General_Language_Latam", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Russian (Русский).
        /// </summary>
        public static string Settings_General_Language_Russian {
            get {
                return ResourceManager.GetString("Settings_General_Language_Russian", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Spanish - Spain (Español de España).
        /// </summary>
        public static string Settings_General_Language_Spanish {
            get {
                return ResourceManager.GetString("Settings_General_Language_Spanish", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to System default (System default).
        /// </summary>
        public static string Settings_General_Language_System {
            get {
                return ResourceManager.GetString("Settings_General_Language_System", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (Türkçe).
        /// </summary>
        public static string Settings_General_Language_Turkish {
            get {
                return ResourceManager.GetString("Settings_General_Language_Turkish", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Run when Windows starts.
        /// </summary>
        public static string Settings_General_RunOnWindowsStartup {
            get {
                return ResourceManager.GetString("Settings_General_RunOnWindowsStartup", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_General_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string Settings_General_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Settings_General_UpdateOnStartup", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Clean up video titles.
        /// </summary>
        public static string Settings_Scrobbling_CleanTitles {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_CleanTitles", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Removes tags such as "(Official Video)" and splits "Artist - Title" when YouTube [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Scrobbling_CleanTitles_Description {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_CleanTitles_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Only videos detected as music are scrobbled unless enabled below. Song, artist a [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Scrobbling_Description {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to API key.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_ApiKey {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_ApiKey", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to API secret.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_ApiSecret {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_ApiSecret", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Enable Last.FM scrobbling.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_Enable {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_Enable", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_Password {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_Password", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Save credentials.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_SaveCredentials {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_SaveCredentials", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Last.FM.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_Username {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_Username", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Enable ListenBrainz scrobbling.
        /// </summary>
        public static string Settings_Scrobbling_ListenBrainz_Enable {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ListenBrainz_Enable", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ListenBrainz.
        /// </summary>
        public static string Settings_Scrobbling_ListenBrainz_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ListenBrainz_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to User token.
        /// </summary>
        public static string Settings_Scrobbling_ListenBrainz_UserToken {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ListenBrainz_UserToken", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Only scrobble the first artist.
        /// </summary>
        public static string Settings_Scrobbling_ScrobblePrimaryArtist {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ScrobblePrimaryArtist", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Maximum scrobble wait:.
        /// </summary>
        public static string Settings_Scrobbling_ScrobbleTime {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ScrobbleTime", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to After this amount of time has passed, scrobble the song if it hasn't been scrobb [rest of string was truncated]";..
        /// </summary>
        public static string Settings_Scrobbling_ScrobbleTime_Description {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ScrobbleTime_Description", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Also scrobble videos that are not music.
        /// </summary>
        public static string Settings_Scrobbling_ScrobbleVideos {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ScrobbleVideos", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Scrobbling.
        /// </summary>
        public static string Settings_Scrobbling_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_SectionTitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Scrobbling.
        /// </summary>
        public static string Settings_Scrobbling_SectionTitleShort {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_SectionTitleShort", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string Settings_TimeUnitSeconds {
            get {
                return ResourceManager.GetString("Settings_TimeUnitSeconds", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Taskbar_Exit_Title {
            get {
                return ResourceManager.GetString("Taskbar_Exit_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Taskbar_Settings_Title {
            get {
                return ResourceManager.GetString("Taskbar_Settings_Title", resourceCulture);
            }
        }
    }
}
